### ISSUE TITLE
Add Tracktion Waveform 9?

### ISSUE THREAD

**Issue by ryanpcmcquen** [ahahn94/my-3rd-party#8]
Any chance you could add this? Pretty please!

**Comment by ahahn94** [comment]
Tracktion T7 was already in the repo.

I have added Tracktion Waveform to the repo. The package is almost identical to the T7 package, so this was a fast build.
This is not the latest version. Version 9.3.2 crashed right after launch. As you can see [here](https://aur.archlinux.org/packages/tracktion-waveform/), this version seems to be buggy.
I used version 3.2.1 instead, which seems to be working fine.

**Comment by ahahn94** [comment]
I will not update this package on a regular basis, so if you want a newer version in the future, please create a new issue.

**Comment by ryanpcmcquen** [comment]
Woohoo, thanks! Hopefully the next release fixes those issues.

**Comment by ahahn94** [comment]
Yeah, as one comment on the AUR page I linked earlier mentions, the beta version seems to work fine.
But as I do not want to create a tracktion account just to search for the download link to the beta, I will use the link to the cdn from the AUR, which is the stable version. Also, I want the package to contain the normal release, not the beta one.
